function cloneTree(nodes) {
  return nodes.map((node) => ({
    ...node,
    children: node.children ? cloneTree(node.children) : [],
  }));
}

function hasChildNamed(parent, name) {
  return parent.children?.some((child) => child.name === name);
}

function pushIfMissing(parent, node) {
  if (!hasChildNamed(parent, node.name)) {
    parent.children.push(node);
  }
}

const reactWarningText =
  "This scaffold uses Vite 8. Use Node.js 20.19+ or 22.12+ before running";

function getReactAppCss() {
  return `.app-shell {
  min-height: 100vh;
  display: grid;
  place-items: center;
  padding: 24px;
  background:
    radial-gradient(circle at top left, rgba(99, 102, 241, 0.18), transparent 30%),
    radial-gradient(circle at top right, rgba(56, 189, 248, 0.1), transparent 28%),
    linear-gradient(180deg, #020617 0%, #071127 100%);
}

.hero-card {
  width: min(760px, 100%);
  padding: 32px;
  border-radius: 24px;
  background: rgba(15, 23, 42, 0.78);
  border: 1px solid rgba(148, 163, 184, 0.14);
  box-shadow: 0 24px 50px rgba(0, 0, 0, 0.35);
  backdrop-filter: blur(12px);
}

.badge {
  display: inline-block;
  margin-bottom: 16px;
  padding: 8px 12px;
  border-radius: 999px;
  background: rgba(99, 102, 241, 0.16);
  border: 1px solid rgba(99, 102, 241, 0.24);
  color: #c7d2fe;
  font-size: 13px;
  font-weight: 700;
}

.hero-title {
  margin: 0 0 14px;
  font-size: clamp(2rem, 5vw, 3.2rem);
  line-height: 1.08;
  color: #f8fafc;
}

.subtitle {
  margin: 0 0 24px;
  color: #94a3b8;
  font-size: 1rem;
}

.warning-box {
  margin-bottom: 20px;
  padding: 14px 16px;
  border-radius: 16px;
  background: rgba(245, 158, 11, 0.12);
  border: 1px solid rgba(245, 158, 11, 0.28);
  color: #fde68a;
}

.warning-title {
  margin: 0 0 6px;
  font-size: 14px;
  font-weight: 800;
  color: #fef3c7;
}

.warning-text {
  margin: 0;
  font-size: 14px;
  line-height: 1.6;
}

.steps {
  display: grid;
  gap: 12px;
}

.step {
  padding: 14px 16px;
  border-radius: 14px;
  background: rgba(255, 255, 255, 0.04);
  border: 1px solid rgba(148, 163, 184, 0.1);
  color: #e2e8f0;
}

code {
  background: rgba(255, 255, 255, 0.08);
  padding: 2px 8px;
  border-radius: 6px;
  font-family: Consolas, "Fira Code", monospace;
}`;
}

function getReactIndexCss(withTailwind) {
  if (withTailwind) {
    return `@tailwind base;
@tailwind components;
@tailwind utilities;

html,
body,
#root {
  margin: 0;
  min-height: 100%;
}`;
  }

  return `:root {
  font-family: Inter, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI",
    sans-serif;
  color: #e5e7eb;
  background: #020617;
  line-height: 1.5;
  font-weight: 400;
}

* {
  box-sizing: border-box;
}

html,
body,
#root {
  margin: 0;
  min-height: 100%;
}

body {
  min-width: 320px;
  min-height: 100vh;
  background: #020617;
  color: #e2e8f0;
}`;
}

function getReactMainFile(withTypeScript) {
  const appFile = withTypeScript ? "./App.tsx" : "./App.jsx";
  return `import React from "react";
import ReactDOM from "react-dom/client";
import App from "${appFile}";
import "./index.css";

ReactDOM.createRoot(document.getElementById("root")${
    withTypeScript ? "!" : ""
  }).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);`;
}

function getReactAppFile({ withTailwind, withTypeScript }) {
  const appFileName = withTypeScript ? "src/App.tsx" : "src/App.jsx";

  if (withTailwind) {
    return `export default function App() {
  return (
    <main className="min-h-screen bg-slate-950 text-slate-100">
      <div className="min-h-screen bg-[radial-gradient(circle_at_top_left,rgba(99,102,241,0.18),transparent_30%),radial-gradient(circle_at_top_right,rgba(56,189,248,0.10),transparent_28%),linear-gradient(180deg,#020617_0%,#071127_100%)] px-6 py-10">
        <div className="mx-auto grid min-h-[80vh] max-w-4xl place-items-center">
          <section className="w-full rounded-3xl border border-slate-700/40 bg-slate-900/70 p-8 shadow-2xl backdrop-blur-xl md:p-10">
            <span className="inline-flex rounded-full border border-indigo-400/25 bg-indigo-500/15 px-3 py-2 text-sm font-semibold text-indigo-200">
              Generated by Folder Structure Visualizer
            </span>

            <h1 className="mt-5 text-4xl font-extrabold tracking-tight text-white md:text-6xl">
              React + Vite + Tailwind ${withTypeScript ? "TSX " : ""}scaffold ready
            </h1>

            <p className="mt-4 max-w-2xl text-base leading-7 text-slate-400 md:text-lg">
              Your frontend starter has been generated successfully. Start
              building from{" "}
              <code className="rounded bg-white/10 px-2 py-1 text-slate-100">
                ${appFileName}
              </code>
            </p>

            <div className="mt-6 rounded-2xl border border-amber-400/25 bg-amber-500/10 p-4 text-amber-100">
              <p className="text-sm font-extrabold tracking-wide text-amber-50">
                Node.js requirement
              </p>
              <p className="mt-2 text-sm leading-6 text-amber-100/90">
                ${reactWarningText}{" "}
                <code className="rounded bg-white/10 px-2 py-1 text-slate-100">
                  npm install
                </code>{" "}
                and{" "}
                <code className="rounded bg-white/10 px-2 py-1 text-slate-100">
                  npm run dev
                </code>.
              </p>
            </div>

            <div className="mt-8 grid gap-3">
              <div className="rounded-2xl border border-slate-700/40 bg-white/5 p-4 text-slate-200">
                Edit{" "}
                <code className="rounded bg-white/10 px-2 py-1">
                  ${appFileName}
                </code>
              </div>
              <div className="rounded-2xl border border-slate-700/40 bg-white/5 p-4 text-slate-200">
                Create components in{" "}
                <code className="rounded bg-white/10 px-2 py-1">
                  src/components
                </code>
              </div>
              <div className="rounded-2xl border border-slate-700/40 bg-white/5 p-4 text-slate-200">
                Run{" "}
                <code className="rounded bg-white/10 px-2 py-1">
                  npm install
                </code>{" "}
                and{" "}
                <code className="rounded bg-white/10 px-2 py-1">
                  npm run dev
                </code>
              </div>
            </div>
          </section>
        </div>
      </div>
    </main>
  );
}`;
  }

  if (withTypeScript) {
    return `import "./App.css";

function App() {
  return (
    <div className="app-shell">
      <div className="hero-card">
        <span className="badge">Generated by Folder Structure Visualizer</span>

        <h1 className="hero-title">React + Vite TSX scaffold ready</h1>

        <p className="subtitle">
          Your frontend starter has been generated successfully. Start building
          from <code>${appFileName}</code>.
        </p>

        <div className="warning-box">
          <p className="warning-title">Node.js requirement</p>
          <p className="warning-text">
            ${reactWarningText} <code>npm install</code> and <code>npm run dev</code>.
          </p>
        </div>

        <div className="steps">
          <div className="step">
            Edit <code>${appFileName}</code>
          </div>
          <div className="step">
            Create components in <code>src/components</code>
          </div>
          <div className="step">
            Run <code>npm install</code> and <code>npm run dev</code>
          </div>
        </div>
      </div>
    </div>
  );
}

export default App;
`;
  }

  return `import "./App.css";

function App() {
  return (
    <div className="app-shell">
      <div className="hero-card">
        <span className="badge">Generated by Folder Structure Visualizer</span>

        <h1 className="hero-title">React + Vite scaffold ready</h1>

        <p className="subtitle">
          Your frontend starter has been generated successfully. Start building
          from <code>${appFileName}</code>.
        </p>

        <div className="warning-box">
          <p className="warning-title">Node.js requirement</p>
          <p className="warning-text">
            ${reactWarningText} <code>npm install</code> and <code>npm run dev</code>.
          </p>
        </div>

        <div className="steps">
          <div className="step">
            Edit <code>${appFileName}</code>
          </div>
          <div className="step">
            Create components in <code>src/components</code>
          </div>
          <div className="step">
            Run <code>npm install</code> and <code>npm run dev</code>
          </div>
        </div>
      </div>
    </div>
  );
}

export default App;`;
}

function getViteConfigFile(withTypeScript) {
  return `import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

export default defineConfig({
  plugins: [react()],
});`;
}

function getPackageJson({ withTailwind, withTypeScript }) {
  return JSON.stringify(
    {
      name: "frontend",
      private: true,
      version: "0.0.0",
      type: "module",
      scripts: {
        dev: "vite",
        build: "vite build",
        preview: "vite preview",
      },
      dependencies: {
        react: "^18.3.1",
        "react-dom": "^18.3.1",
      },
      devDependencies: {
        vite: "^8.0.1",
        "@vitejs/plugin-react": "^6.0.1",
        ...(withTypeScript
          ? {
              typescript: "^5.6.3",
              "@types/react": "^18.3.12",
              "@types/react-dom": "^18.3.1",
            }
          : {}),
        ...(withTailwind
          ? {
              tailwindcss: "^3.4.13",
              postcss: "^8.5.8",
              autoprefixer: "^10.4.27",
            }
          : {}),
      },
    },
    null,
    2,
  );
}

function createReactVitePreset(withTailwind = false, withTypeScript = false) {
  const appFileName = withTypeScript ? "App.tsx" : "App.jsx";
  const mainFileName = withTypeScript ? "main.tsx" : "main.jsx";
  const viteConfigFileName = withTypeScript
    ? "vite.config.ts"
    : "vite.config.js";

  return {
    name: "frontend",
    type: "folder",
    children: [
      {
        name: ".gitignore",
        type: "file",
        content: `node_modules
dist
.vite
.DS_Store`,
      },
      {
        name: "package.json",
        type: "file",
        content: getPackageJson({ withTailwind, withTypeScript }),
      },
      {
        name: "index.html",
        type: "file",
        content: `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Frontend</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/${mainFileName}"></script>
  </body>
</html>`,
      },
      {
        name: viteConfigFileName,
        type: "file",
        content: getViteConfigFile(withTypeScript),
      },
      {
        name: "public",
        type: "folder",
        children: [],
      },
      {
        name: "src",
        type: "folder",
        children: [
          {
            name: "assets",
            type: "folder",
            children: [],
          },
          {
            name: "components",
            type: "folder",
            children: [],
          },
          {
            name: "utils",
            type: "folder",
            children: [],
          },
          {
            name: mainFileName,
            type: "file",
            content: getReactMainFile(withTypeScript),
          },
          {
            name: appFileName,
            type: "file",
            content: getReactAppFile({ withTailwind, withTypeScript }),
          },
          ...(withTailwind
            ? []
            : [
                {
                  name: "App.css",
                  type: "file",
                  content: getReactAppCss(),
                },
              ]),
          {
            name: "index.css",
            type: "file",
            content: getReactIndexCss(withTailwind),
          },
          ...(withTypeScript
            ? [
                {
                  name: "vite-env.d.ts",
                  type: "file",
                  content: `/// <reference types="vite/client" />`,
                },
              ]
            : []),
        ],
      },
      ...(withTailwind
        ? [
            {
              name: "tailwind.config.js",
              type: "file",
              content: `/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {},
  },
  plugins: [],
};`,
            },
            {
              name: "postcss.config.js",
              type: "file",
              content: `export default {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};`,
            },
          ]
        : []),
      ...(withTypeScript
        ? [
            {
              name: "tsconfig.json",
              type: "file",
              content: `{
  "files": [],
  "references": [
    { "path": "./tsconfig.app.json" },
    { "path": "./tsconfig.node.json" }
  ]
}`,
            },
            {
              name: "tsconfig.app.json",
              type: "file",
              content: `{
  "compilerOptions": {
    "tsBuildInfoFile": "./node_modules/.tmp/tsconfig.app.tsbuildinfo",
    "target": "ES2020",
    "useDefineForClassFields": true,
    "lib": ["ES2020", "DOM", "DOM.Iterable"],
    "module": "ESNext",
    "skipLibCheck": true,
    "moduleResolution": "Bundler",
    "allowImportingTsExtensions": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "moduleDetection": "force",
    "noEmit": true,
    "jsx": "react-jsx",
    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noFallthroughCasesInSwitch": true
  },
  "include": ["src"]
}`,
            },
            {
              name: "tsconfig.node.json",
              type: "file",
              content: `{
  "compilerOptions": {
    "tsBuildInfoFile": "./node_modules/.tmp/tsconfig.node.tsbuildinfo",
    "target": "ES2022",
    "lib": ["ES2023"],
    "module": "ESNext",
    "skipLibCheck": true,
    "moduleResolution": "Bundler",
    "allowImportingTsExtensions": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "moduleDetection": "force",
    "noEmit": true,
    "strict": true
  },
  "include": ["vite.config.ts"]
}`,
            },
          ]
        : []),
    ],
  };
}

function createExpressPreset() {
  return {
    name: "backend",
    type: "folder",
    children: [
      {
        name: "package.json",
        type: "file",
        content: JSON.stringify(
          {
            name: "backend",
            version: "1.0.0",
            main: "src/server.js",
            scripts: {
              dev: "node src/server.js",
              start: "node src/server.js",
            },
            dependencies: {
              express: "^4.21.0",
            },
          },
          null,
          2,
        ),
      },
      {
        name: "src",
        type: "folder",
        children: [
          {
            name: "server.js",
            type: "file",
            content: `const express = require("express");

const app = express();
const PORT = process.env.PORT || 5000;

app.get("/", (req, res) => {
  res.send("Backend API is running");
});

app.listen(PORT, () => {
  console.log(\`Server running on port \${PORT}\`);
});`,
          },
        ],
      },
    ],
  };
}

function createGitignoreFile() {
  return {
    name: ".gitignore",
    type: "file",
    content: `node_modules
dist
build
.vite
.env
.DS_Store`,
  };
}

function ensureRoot(tree) {
  if (!tree.length) {
    return [
      {
        name: "project",
        type: "folder",
        children: [],
      },
    ];
  }

  if (tree.length === 1 && tree[0].type === "folder") {
    return tree;
  }

  return [
    {
      name: "project",
      type: "folder",
      children: tree,
    },
  ];
}

export function applyScaffoldPresets(treeData, options) {
  const clonedTree = ensureRoot(cloneTree(treeData));
  const root = clonedTree[0];

  if (options.reactVite) {
    pushIfMissing(
      root,
      createReactVitePreset(options.tailwind, options.typescript),
    );
  }

  if (options.expressBackend) {
    pushIfMissing(root, createExpressPreset());
  }

  if (options.gitignore) {
    pushIfMissing(root, createGitignoreFile());
  }

  return clonedTree;
}
